version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: air_quality_db_root_pass
      MYSQL_DATABASE: air_quality_db
      MYSQL_USER: air_quality_db_user
      MYSQL_PASSWORD: air_quality_db_pass
    ports:
      - "3306:3306"

  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db