# Generated by Django 5.1.3 on 2024-12-07 11:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('error', 'Error')], max_length=20)),
                ('records_processed', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AirQualityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('pollutant', models.CharField(max_length=50)),
                ('concentration', models.FloatField()),
                ('units', models.CharField(max_length=20)),
                ('ingested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(max_length=200)),
            ],
            options={
                'indexes': [models.Index(fields=['station_id', 'timestamp'], name='air_quality_station_a36fa9_idx')],
                'unique_together': {('station_id', 'timestamp', 'pollutant')},
            },
        ),
    ]
