# Generated by Django 5.1.3 on 2024-12-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_quality_pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airqualityrecord',
            name='carbon_monoxide',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='airqualityrecord',
            name='nitrogen_dioxide',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='airqualityrecord',
            name='ozone',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='airqualityrecord',
            name='pm10',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='airqualityrecord',
            name='pm25',
            field=models.FloatField(default=0.0),
        ),
    ]
