# Generated by Django 5.1.3 on 2024-12-08 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('air_quality_pipeline', '0002_airqualityrecord_carbon_monoxide_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='airqualityrecord',
            unique_together=set(),
        ),
    ]
